name: hoomee
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  path_provider: ^2.0.1
  hive: ^2.0.0
  rxdart: ^0.26.0
  connectivity: ^3.0.2
  flutter_spinkit: ^5.0.0
  percent_indicator: ^3.3.0-nullsafety.1
  image_picker: ^0.7.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/drawables/images/
    - assets/drawables/icons/
    - assets/drawables/icons/2.0x/
    - assets/drawables/icons/3.0x/

flutter_intl:
  enabled: true
